supermarket/axf/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.staticfiles.urls import static

from axf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('users.urls',namespace='user')),
    url(r'^home/', include('home.urls',namespace='home')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

supermarket/home/urls.py
from django.conf.urls import url
from home import views


urlpatterns = [
# 首页
url(r'^index/',views.index,name='index'),
# 闪购页面
url(r'^market/',views.market,name='market'),
url(r'^market_params/(?P<typeid>\d+)/(?P<cid>\d+)/(?P<sid>\d+)/',views.market_params,name='market_params'),
# 添加商品
url(r'^add_To_Cart/',views.add_To_Cart,name='add_To_Cart'),
# 删除商品
url(r'^desc_To_Cart/',views.desc_To_Cart,name='desc_To_Cart'),
# 刷新闪购页面商品初始值
url(r'^refresh_goods/',views.refresh_goods,name='refresh_goods'),
# 购物车
url(r'^cart/',views.cart,name='cart'),

# 改变购物车中商品的勾选状态
url(r'^change_cart_goods/',views.change_cart_goods,name='change_cart_goods'),
# # 改变所有商品的勾选状态
url(r'^change_all_cart_goods/',views.change_all_cart_goods,name='change_all_cart_goods'),

# 计算总价
url(r'^goods_count/',views.goods_count,name='goods_count'),
# 订单
url(r'^order/',views.order,name='order'),
# 下单信息
url(r'^order_info/',views.order_info,name='order_info'),
# 下单支付
url(r'^order_pay/',views.order_pay,name='order_pay'),
# 待付款
url(r'^wait_to_pay/',views.wait_to_pay,name='wait_to_pay'),

# 付款未发货
url(r'^paid/',views.paid,name='paid'),


]

supermarket/templates/market/market.html
{% extends 'base_main.html' %}
{% load static %}
{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'app/market/market.css' %}">
{% endblock %}

{% block EXTJS %}
    <script type="text/javascript" src="{% static 'app/market/js/market.js' %}"></script>
    <script type="text/javascript" src="{% static 'app/cart/common/function.js' %}"></script>
{% endblock %}


{% block content %}

    <div id="market">

        <aside>

            <ul>

                <!--闪购分类展示-->
                {% for type in foodtypes %}
                    <li>
                        <!--链接地址，点击获取分类下的商品信息-->
                        <a href="{% url 'home:market_params' type.typeid 0 0%}">{{ type.typename }}</a>
                        {% ifequal typeid type.typeid%}
                            <span class="yellowSlide"></span>
                        {% endifequal %}
                    </li>
                {% endfor %}
                <!--处理数据结束-->

            </ul>

        </aside>


        <section>
            <nav>
                <ul>

                    <li id="all_types"><span>全部类型<span id="all_type_logo"
                    class="glyphicon glyphicon-chevron-down"></span></span></li>


                    <li id="sort_rule"><span>综合排序<span id="sort_rule_logo" class="glyphicon glyphicon-chevron-down"></span></span></li>

                </ul>
            </nav>

            <menu>
                <ul>

                    <!--商品信息展示-->
                    {% for good in goods %}
                        <li>
                            <a href="#">
                                <img src="{{ good.productimg }}" alt="">
                                <div class="shoppingInfo">
                                    <h6>{{ productlongname }}</h6>
                                    <p class="detailTag">
                                        <span>精选</span>
                                        <span>{{ good.productname }}</span>
                                    </p>
                                    <p class="unit">
                                    {{ good.specifics }}
                                    </p>
                                    <p class="price">
                                        <span>¥{{ good.price }}</span>
                                        <s>¥{{ good.marketprice }}</s>
                                    </p>
                                </div>
                            </a>
                        <section>
                            {% csrf_token %}

                            <button onclick="desc_To_Cart({{ good.id }})">-</button>
                            <span id="num_{{ good.id }}">0</span>
                            <button onclick="add_To_Cart({{ good.id }})">+</button>
                        </section>
                        </li>
                    {% endfor %}
                    <!--处理数据结束-->
                </ul>

                <div id="all_types_container">
                    <div>
                        <!--加载全部分类的数据-->

                        {% for childtype  in  childtypes %}
                            <a href="{% url 'home:market_params' typeid childtype.1 sid %}">
                                <span>{{ childtype.0 }}</span>
                            </a>
                        {% endfor %}
                        <!--处理数据结束-->


                    </div>
                </div>


                <div id="sort_container">
                    <div>
                    {#排序传递的也是状态码   0 , 1 ,2  , 3 ,4 ,5...  #}
                        <a href="{% url 'home:market_params' typeid cid 0 %}">
                            <span>综合排序</span>
                        </a>
                        <a href="{% url 'home:market_params' typeid cid 1  %}">
                            <span>销量排序</span>
                        </a>
                        <a href="{% url 'home:market_params' typeid cid 2 %}">
                            <span>价格降序</span>
                        </a>
                        <a href="{% url 'home:market_params' typeid cid 3 %}">
                            <span>价格升序</span>
                        </a>

                    </div>
                </div>

            </menu>

        </section>


    </div>


{% endblock %}