supermarket/axf/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.staticfiles.urls import static

from axf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('users.urls',namespace='user')),
    url(r'^home/', include('home.urls',namespace='home')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

supermarket/home/urls.py
from django.conf.urls import url
from home import views


urlpatterns = [
# 首页
url(r'^index/',views.index,name='index'),
# 闪购页面
url(r'^market/',views.market,name='market'),
url(r'^market_params/(?P<typeid>\d+)/(?P<cid>\d+)/(?P<sid>\d+)/',views.market_params,name='market_params'),
# 添加商品
url(r'^add_To_Cart/',views.add_To_Cart,name='add_To_Cart'),
# 删除商品
url(r'^desc_To_Cart/',views.desc_To_Cart,name='desc_To_Cart'),
# 刷新闪购页面商品初始值
url(r'^refresh_goods/',views.refresh_goods,name='refresh_goods'),
# 购物车
url(r'^cart/',views.cart,name='cart'),

# 改变购物车中商品的勾选状态
url(r'^change_cart_goods/',views.change_cart_goods,name='change_cart_goods'),
# # 改变所有商品的勾选状态
url(r'^change_all_cart_goods/',views.change_all_cart_goods,name='change_all_cart_goods'),

# 计算总价
url(r'^goods_count/',views.goods_count,name='goods_count'),
# 订单
url(r'^order/',views.order,name='order'),
# 下单信息
url(r'^order_info/',views.order_info,name='order_info'),
# 下单支付
url(r'^order_pay/',views.order_pay,name='order_pay'),
# 待付款
url(r'^wait_to_pay/',views.wait_to_pay,name='wait_to_pay'),

# 付款未发货
url(r'^paid/',views.paid,name='paid'),


]

supermarket/users/urls.py
from django.conf.urls import url
from users import views



urlpatterns = [
    # 个人中心
    url(r'^mine/',views.mine,name='mine'),
    # 注册
    url(r'^register/',views.register,name='register'),
    # 登录
    url(r'^login/',views.login,name='login'),
    # 注销
    url(r'^logout/',views.logout,name='logout')

]

supermarket/templates/mine/mine.html
{% extends 'base_main.html' %}
{% load static %}
{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'app/mine/mine.css' %}">
{% endblock %}

{% block EXTJS %}
{{ block.super }}
    <script type="text/javascript" src="{% static 'app/mine/js/mine.js' %}"></script>
{% endblock %}

{% block content %}

    <div id="mine" >


        <div class="fixed" >
            <!--如果登录，展示头像-->

            {% if user.id %}
                <img src="/media/{{ user.icon }}" alt="icon" >
            {% else %}
            <!--或者-->
                <span class="glyphicon glyphicon-user"></span>
            {% endif %}
            <!--判断结束-->

            <!--如果登录，展示姓名-->
            {% if user.id %}
                <p>{{ user.username }}</p>
            {% else %}
            <!--或者展示登录的链接-->
                <a href=""></a>
            {% endif %}
            <!--判断结束-->



            <p><span class="glyphicon glyphicon-fire"></span><span>等级</span></p>
            <!--如果没有登录,展示注册信息-->
            {% if user.id %}
                <div id="login">
                    <p>{{ user.id }}</p>
                </div>

            {% else %}
                <div id="regis">

                    <a href="{% url 'user:register' %}">注册</a>
                    <a href="{% url 'user:login' %}">登录</a>

                </div>
            {% endif %}
            <!--判断结束-->

            <p><span class="glyphicon glyphicon-heart"></span><span>收藏</span></p>

        </div>

        <div class="mine">

            <p>我的订单<a href="#">更多&gt;</a></p>

            <div id="nav">

                <ul>
                    <li>
                        <dl>
                            <dt><span id="wait_pay_list" class="glyphicon glyphicon-usd"></span>
                                <span class="badge">
                                    <!--待付款的数量-->
                                {{ wait_pay }}
                                </span></dt>

                            <a href="{% url 'home:wait_to_pay' %}">
                                <dd>待付款</dd>
                            </a>

                        </dl>

                    </li>
                    <li>
                        <dl>
                            <dt><span id="order_payed_list" class="glyphicon glyphicon-envelope"></span>
                                <span class="badge">
                                    <!--待收货的数量-->
                                {{ paid }}
                                </span></dt>

                            <a href="{% url 'home:paid' %}">
                                <dd>待收货</dd>
                            </a>

                        </dl>

                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-pencil"></span></dt>
                            <dd>待评价</dd>
                        </dl>

                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-retweet"></span></dt>
                            <dd>退款/售后</dd>
                        </dl>

                    </li>

                </ul>

            </div>

            <menu>
                <ul>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-bullhorn"></span></dt>
                            <span>积分商城</span>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-credit-card"></span></dt>
                            <span>优惠券</span>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-import"></span></dt>
                            <span>收货地址</span>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-phone-alt"></span></dt>
                            <span>客户反馈</span>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-certificate"></span></dt>
                            <span>关于我们</span>
                        </dl>
                    </li>
                </ul>
            </menu>

            <!--如果登录了,则退出展示-->
            {% if user.id %}
                <p class="logout">
                    <a href="{% url 'user:logout' %}">退出</a>
                </p>
            {% endif %}
            <!--判断结束-->
        </div>
    </div>


{% endblock %}