aj/app/views.py
import random
import re
import os
from flask import Blueprint, redirect, \
    render_template, request, url_for, jsonify,session
from app.models import db, User
from utils import status_code
from utils.functions import is_login
from utils.settings import UPLOAD_DIR


# 初始化蓝图对象

user_blueprint = Blueprint('user',__name__)

# 迁移数据表
@user_blueprint.route('/')
def create_all():
    db.create_all()
    return '创建数据库成功'

# 注册（返回页面）
@user_blueprint.route('register/',methods=['GET'])
def register():
    if request.method == 'GET':
        return render_template('register.html')


# 实现注册
@user_blueprint.route('register/',methods=['POST'] )
def my_register():
    # 获取注册页面ajax提交过来的参数：request.form
    mobile = request.form.get('mobile')
    imagecode = request.form.get('imagecode')
    passwd = request.form.get('passwd')
    passwd2 = request.form.get('passwd2')

    # 校验是否填写完整
    if not all([mobile,imagecode,passwd,passwd2]):
        return jsonify(status_code.USER_REGISTER_PARAMS_NOT_EXISTS)
    # 校验手机号
    if not re.match(r'^1[345678]\d{9}$',mobile):
        return jsonify(status_code.USER_REGISTER_PHONE_IS_NOT_VALID)

    # 校验图片验证码
    if session.get('code') != imagecode:
        return jsonify(status_code.USER_REGISTER_CODE_IS_NOT_VALID)

    # 校验密码
    if passwd != passwd2:
        return jsonify(status_code.USER_REGISTER_PASSWORD_IS_NOT_EQUAL)

    # 判断手机是否注册
    user = User.query.filter(User.phone==mobile).all()
    if user:
        return jsonify(status_code.USER_REGISTER_PHONE_IS_EXISTS_ALREADY)
    # 保存用户的注册信息
    user = User()
    user.phone = mobile
    user.name = mobile
    user.password = passwd
    user.add_update()
    return jsonify(status_code.SUCCESS)
#
@user_blueprint.route('img_code/')
def img_code():
    # 获取验证码
    s = '1234567890qwertyuiopasdfghjklzxcvbnm'
    code = ''
    for _ in range(4):
        code += random.choice(s)
    # 将状态码存放在session中
    session['code'] = code
    return jsonify({'code':200,'msg':'请求成功','data':code})



# 登录(页面)
@user_blueprint.route('login/',methods=['GET'])
def login():
    if request.method == "GET":
        return render_template('login.html')

# 实现登录
@user_blueprint.route('my_login/',methods=['GET'])
def my_login():
    if request.method == "GET":
        # 获取手机号和密码
        phone = request.args.get('mobile')
        passwd = request.args.get('passwd')

        # 校验参数是否完整
        if not all([phone,passwd]):
            return jsonify(status_code.USER_LOGIN_PARAMS_NOT_EXISTS)

        # 校验手机号是否符合规格
        if not re.match(r'^1[345678]\d{9}$',phone):
            return jsonify(status_code.USER_LOGIN_PHONE_IS_NOT_VALID)
        # 判断手机号是否存在
        user = User.query.filter(User.phone==phone).first()
        if not user:
            return jsonify(status_code.USER_LOGIN_IS_NOT_EXISTS)
        # 判断密码是否正确
        if not user.check_pwd(passwd):
            return jsonify(status_code.USER_LOGIN_PASSWORD_IS_VALID)
        # 记录用户登录成功
        session['user_id'] = user.id
        return jsonify(status_code.SUCCESS)


@user_blueprint.route('my/',methods=['GET'])
@is_login
def my():
    if request.method == "GET":
        return render_template('my.html')


@user_blueprint.route('my_info/',methods=['GET'])
def my_info():
    user_id = session['user_id']
    user = User.query.get(user_id)
    user_info = user.to_basic_dict()
    return jsonify(user_info=user_info,code=status_code.SUCCESS)

# def log(func):
#     user_id = session.get('user_id')
#     user = User.query.get(user_id)

@user_blueprint.route('logout/',methods=['GET'])
@is_login
def logout():
    session.clear()
    return jsonify(status_code.SUCCESS)

@user_blueprint.route('profile/',methods=['GET'])
@is_login
def profile():
    return render_template('profile.html')



@user_blueprint.route('profile/',methods=['PATCH'])
def my_profile():
    # 获取头像

    avatar = request.files.get('avatar')
    user_id = session['user_id']

    if avatar:
        # 保存用户头像，保存在media
        # 保存图片到/static/media/upload/xxx.jpg
        avatar.save(os.path.join(UPLOAD_DIR,avatar.filename))
        # 修改用户的头像字段
        user = User.query.get(user_id)
        upload_avater_path = os.path.join('upload',avatar.filename)
        user.avatar=upload_avater_path
        user.add_update()
        return jsonify(code = status_code.SUCCESS,img_avatar=upload_avater_path)
    else:
        return jsonify(status_code.USER_PROFILES_AVATAR_NOT_EXISTS)

# @user_blueprint.route('orders/',methods=['GET'])
# def my_order():
#     return render_template('orders.html')


@user_blueprint.route('profile_name/',methods=['PATCH'])
def profile_name():
    # 修改用户名
    username = request.form.get('username')
    if not User.query.filter(User.name==username).count():
        user = User.query.get(session['user_id'])
        user.name = username
        user.add_update()
        return jsonify(status_code.SUCCESS)
    else:
        return jsonify(status_code.USERNAME_IS_ALREADY_EXISTS)

    # 获取用户名，校验用户名是否存在
    # 更新用户名


@user_blueprint.route('auth/',methods=['GET'])
@is_login
def auth():
    return render_template('auth.html')


@user_blueprint.route('auth/',methods=['PATCH'])
def my_auth():
    # 获取用户名和身份证号
    # 校验参数

    real_name = request.form.get('real_name')
    id_card = request.form.get('id_card')
    if not all([real_name,id_card]):
        return jsonify(status_code.USER_AUTH_PARAMS_IS_NOT_VALID)
    if not re.match(r'^[1-9]\d{16}[1-9X]$',id_card):
        return jsonify(status_code.USER_AUTH_ID_CARD_IS_NOT_VALID)

    # 修改用户的信息
    user = User.query.get(session['user_id'])
    user.id_card = id_card
    user.id_name = real_name
    user.add_update()
    return jsonify(status_code.SUCCESS)


@user_blueprint.route('auth_info/',methods=['GET'])
@is_login
def auth_info():
    user = User.query.get(session['user_id'])
    user_info = user.to_auth_dict()
    return jsonify(user_info=user_info,code=status_code.SUCCESS)

aj/templates/auth.html
<!DOCTYPE html>
<html>
<head> 
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>爱家-实名认证</title>
    <link href="/static/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="/static/css/reset.css" rel="stylesheet">
    <link href="/static/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet">
    <link href="/static/css/ihome/main.css" rel="stylesheet">
    <link href="/static/css/ihome/profile.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div class="top-bar">
            <div class="nav-bar">
                <h3 class="page-title">实名认证</h3>
                <a class="nav-btn fl" href="{{url_for('user.my')}}"><span><i class="fa fa-angle-left fa-2x"></i></span></a>
            </div>
        </div>
        <div class="menus-con">
            <ul class="menus-list">
                <li>
                    <div class="menu-title">
                        <h3>认证信息</h3>
                    </div>
                    <div class="menu-content">
                        <form id="form-auth" method="post">
                            <div class="form-group">
                                <label for="real-name">真实姓名</label>
                                <input type="text" class="form-control" name="real_name" id="real-name" >
                            </div>
                            <div class="form-group">
                                <label for="id-card">身份证号码</label>
                                <input type="text" class="form-control" name="id_card" id="id-card">
                            </div> 
                            <div class="error-msg"><i class="fa fa-exclamation-circle"></i>信息填写不完整，请补全信息</div>
                            <input type="submit" class="btn btn-success" value="保存">
                        </form>
                    </div>
                </li>
            </ul>
        </div>
        <div class="popup_con">
            <div class="popup">
                <p>保存成功！</p>
            </div>
            
            <div class="mask"></div>
        </div>
        <div class="footer">
            <p><span><i class="fa fa-copyright"></i></span>爱家租房&nbsp;&nbsp;享受家的温馨</p>
        </div> 
    </div>
    
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/jquery.form.min.js"></script>
    <script src="/static/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js"></script>
    <script src="/static/js/ihome/auth.js"></script>
</body>
</html>

aj/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>
        {% block title%}
        Title
        {% endblock %}
    </title>
    {% block css %}
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
{% block header %}
{% endblock %}
{% block content %}
{% endblock %}
{% block footer %}
{% endblock %}


</body>
</html>

aj/templates/base_main.html
{% extends 'base.html'%}
{% block title%}

{% endblock %}


    {% block css %}

    <link href="{{ url_for('static',filename='plugins/bootstrap/css/bootstrap.min.css')  }} " rel="stylesheet">
    <link href="{{ url_for('static',filename='plugins/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet">
    <link href="{{ url_for('static',filename='css/reset.css')}}" rel="stylesheet">
    <link href="{{ url_for('static',filename='css/ihome/main.css')}}" rel="stylesheet">
    {% endblock %}
    {% block js %}
    <script src="{{ url_for('static',filename='js/jquery.min.js')}}"></script>
    <script src="{{ url_for('static',filename='plugins/bootstrap/js/bootstrap.min.js')}}"></script>

    {% endblock %}

aj/templates/index.html
<!DOCTYPE html>
<html>
<head> 
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>爱家</title>
    <link href="/static/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="/static/css/reset.css" rel="stylesheet">
    <link href="/static/plugins/swiper/css/swiper.min.css" rel="stylesheet">
    <link href="/static/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet">
    <link href="/static/css/ihome/main.css" rel="stylesheet">
    <link href="/static/css/ihome/index.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div class="top-bar">
            <img class="logo fl" src="/static/images/logo@128x59.png">
            <div class="register-login fr">
                <a class="btn top-btn btn-theme" href="/register.html">注册</a>
                <a class="btn top-btn btn-theme" href="/login.html">登录</a>
            </div>
            <div class="user-info fr"><span><i class="fa fa-user fa-lg"></i></span>
            <a class="user-name" href="{{url_for('user.my')}}"></a>

            </div>
        </div>
        <div class="swiper-container">
            <div class="swiper-wrapper">
                <!--<div class="swiper-slide">-->
                    <!--<a href="#"><img src="/static/images/home01.jpg"></a>-->
                    <!--<div class="slide-title">房屋标题1</div>-->
                <!--</div>-->
            </div>
            <div class="swiper-pagination"></div>
        </div>
        <div class="search-bar">
            <button class="filter-btn" type="button" data-toggle="modal" data-target="#area-modal"><span class="fl" id="area-btn">选择城区</span><span class="fr"><i class="fa fa-map-marker fa-lg fa-fw"></i></span></button>
            <button class="filter-btn" type="button" data-toggle="modal" data-target="#start-date-modal"><span class="fl" id="start-date-btn">入住日期</span><span class="fr"><i class="fa fa-calendar fa-lg fa-fw"></i></span></button>
            <button class="filter-btn end-date" type="button" data-toggle="modal" data-target="#end-date-modal"><span class="fl" id="end-date-btn">离开日期</span><span class="fr"><i class="fa fa-calendar fa-lg fa-fw"></i></span></button>
            <a class="btn search-btn btn-theme" href="#" onclick="goToSearchPage(this);" area-id="" start-date="" end-date="">搜索</a>
            <div class="modal fade" id="area-modal" tabindex="-1" role="dialog" aria-labelledby="area-label">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="area-label">选择城区</h4>
                        </div>
                        <div class="modal-body">
                            <div class="area-list">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="start-date-modal" tabindex="-1" role="dialog" aria-labelledby="start-date-label">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="start-date-label">入住日期</h4>
                        </div>
                        <div class="modal-body">
                            <div class="date-select" id="start-date"></div>
                            <input type="hidden" id="start-date-input">
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-theme" onclick="setStartDate();">确定</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="end-date-modal" tabindex="-1" role="dialog" aria-labelledby="end-date-label">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="end-date-label">离开日期</h4>
                        </div>
                        <div class="modal-body">
                            <div class="date-select" id="end-date"></div>
                            <input type="hidden" id="end-date-input">
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-theme" onclick="setEndDate();">确定</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer">
            <p><span><i class="fa fa-copyright"></i></span>爱家租房&nbsp;&nbsp;享受家的温馨</p>
        </div>
    </div>
    
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/plugins/swiper/js/swiper.jquery.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js"></script>
    <script src="/static/js/template.js"></script>
    <script src="/static/js/ihome/index.js"></script>
</body>
</html>

aj/templates/lorders.html
<!DOCTYPE html>
<html>
<head> 
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>爱家-我的订单</title>
    <link href="/static/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="/static/css/reset.css" rel="stylesheet">
    <link href="/static/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet">
    <link href="/static/css/ihome/main.css" rel="stylesheet">
    <link href="/static/css/ihome/orders.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div class="top-bar">
            <div class="nav-bar">
                <h3 class="page-title">客户订单</h3>
                <a class="nav-btn fl" href="{{url_for('user.my')}}"><span><i class="fa fa-angle-left fa-2x"></i></span></a>
            </div>
        </div>
        <div class="orders-con">
            <ul class="orders-list">
                {% raw %}
                <script type="text/html" id="lorder_tem_script">
                 {{if orders}}
                 {{each orders as order}}
                <li order-id={{order.order_id}}>
                    <div class="order-title">
                        <h3>订单编号：{{order.order_id}}</h3>
                        <div class="fr order-operate">

                            {{if order.status == 'WAIT_ACCEPT'}}
                            <button type="button" class="btn btn-success order-accept" data-toggle="modal" data-target="#accept-modal">接单</button>
                            <button type="button" class="btn btn-danger order-reject" data-toggle="modal" data-target="#reject-modal">拒单</button>
                            {{/if}}
                            {{if order.status == 'WAIT_PAYMENT'}}
                            <button type="button" class="btn btn-danger " data-toggle="modal" >待支付</button>
                            {{/if}}
                            {{if order.status == 'REJECTED'}}
                            <button type="button" class="btn btn-danger order-reject" data-toggle="modal" data-target="#reject-modal">已拒单</button>
                            {{/if}}
                            {{if order.status != 'WAIT_ACCEPT'}}
                            <button type="button" class="btn btn-danger order-delete" data-toggle="modal" data-target="#delete-modal">删除订单</button>
                            {{/if}}

                        </div>
                    </div>
                    <div class="order-content">
                        <img src="/static/media/{{order.image}}">
                        <div class="order-text">
                            <h3>房屋标题</h3>
                            <ul>
                                <li>创建时间：{{order.create_date}}</li>
                                <li>入住日期：{{order.begin_date}}</li>
                                <li>离开日期：{{order.end_date}}</li>
                                <li>合计金额：￥{{order.amount}}(共{{order.days}}晚)</li>
                                <li>订单状态：
                                    <span>{{order.status}}</span>
                                </li>
                                {{if order.status == 'REJECTED'}}
                                <li>拒单理由：{{order.comment}}</li>
                                {{/if}}
                            </ul>
                        </div> 
                    </div>
                </li>
                {{/each}}
                {{/if}}
                </script>
                {% endraw %}
            </ul>
            <div class="modal fade" id="accept-modal" tabindex="-1" role="dialog" aria-labelledby="accept-label">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title">操作提示</h4>
                        </div>
                        <div class="modal-body">
                            <p>您确定接此订单吗？</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                            <button type="button" class="btn btn-primary modal-accept">确定接单</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="reject-modal" tabindex="-1" role="dialog" aria-labelledby="reject-label">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title">请输入拒接单原因</h4>
                        </div>
                        <div class="modal-body">
                            <textarea class="form-control" rows="3" id="reject-reason" placeholder="此处必须填写原因"></textarea>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                            <button type="button" class="btn btn-primary modal-reject">确定</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="delete-modal" tabindex="-1" role="dialog" aria-labelledby="delete-label">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title">操作提示</h4>
                        </div>
                        <div class="modal-body">
                            <p>您确定删除订单吗？</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                            <button type="button" class="btn btn-primary modal-delete">确定删除</button>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="footer">
            <p><span><i class="fa fa-copyright"></i></span>爱家租房&nbsp;&nbsp;享受家的温馨</p>
        </div> 
    </div>
    
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js"></script>
    <script src="/static/js/template.js"></script>
    <script src="/static/js/ihome/lorders.js"></script>
</body>
</html>

aj/templates/my.html
{% extends 'base_main.html' %}
{% block title %}
爱家-我的爱家
{% endblock%}
{% block css %}
{{super()}}
    <link href="/static/css/ihome/main.css" rel="stylesheet">
    <link href="/static/css/ihome/my.css" rel="stylesheet">
{% endblock %}
{% block content %}
    <div class="container">
        <div class="top-bar">
            <div class="nav-bar">
                <h3 class="page-title">我的爱家</h3>
                <a class="nav-btn fl" href="/"><span><i class="fa fa-angle-left fa-2x"></i></span></a>
            </div>
        </div>
        <div class="menus-con">
            <ul class="menus-list">
                <li>
                    <div class="menu-title">
                        <h3>个人信息</h3>
                        <a class="fr" href="{{url_for('user.profile')}}">修改</a>
                    </div>
                    <div class="menu-content">
                        <img id="user-avatar" src="">
                        <div class="menu-text">
                            <h3>用户名：<span id="user-name"></span></h3>
                            <h5>手机号：<span id="user-mobile"></span></h5>
                        </div> 
                    </div>
                </li>
                <li>
                    <div class="menu-title menu-radius">
                        <a href="{{url_for('house.index')}}"><h3>首页</h3></a>
                    </div>
                </li>
                <li>
                    <div class="menu-title menu-radius">
                        <a href="{{url_for('order.orders')}}"><h3>我的订单</h3></a>
                    </div>
                </li>
                <li>
                    <div class="menu-title menu-radius">
                        <a href="{{url_for('user.auth')}}"><h3>实名认证</h3></a>
                    </div>
                </li>
                <li>
                    <div class="menu-title menu-radius">
                        <a href="{{url_for('house.my_house')}}"><h3>我的房源</h3></a>
                    </div>
                </li>
                <li>
                    <div class="menu-title menu-radius">
                        <a href="{{url_for('order.lorders')}}"><h3>客户订单</h3></a>
                    </div>
                </li>
                <li>
                    <div class="menu-title menu-radius">
                        <a href="{{url_for('user.logout')}}" onclick="logout();" >退出</a>
                    </div>
                </li>
            </ul>
        </div>
        <div class="footer">
            <p><span><i class="fa fa-copyright"></i></span>爱家租房&nbsp;&nbsp;享受家的温馨</p>
        </div> 
    </div>
{% endblock %}
{% block js%}
{{super()}}
    <script src="/static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js"></script>
    <script src="/static/js/ihome/my.js"></script>
{% endblock %}

aj/templates/myhouse.html
<!DOCTYPE html>
<html>
<head> 
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>爱家-我的房源</title>
    <link href="/static/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="/static/css/reset.css" rel="stylesheet">
    <link href="/static/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet">
    <link href="/static/css/ihome/main.css" rel="stylesheet">
    <link href="/static/css/ihome/myhouse.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div class="top-bar">
            <div class="nav-bar">
                <h3 class="page-title">我的房源</h3>
                <a class="nav-btn fl" href="{{url_for('user.my')}}"><span><i class="fa fa-angle-left fa-2x"></i></span></a>
            </div>
        </div>
        <div class="houses-con">
            <ul class="houses-list auth-warn">
                <li>
                    <div class="house-title">
                        <h3>尚未进行实名认证，无法发布房屋信息！</h3>
                    </div>
                    <div class="house-content">
                        <a href="{{url_for('user.my_auth')}}" class="btn btn-success">去实名认证</a>
                    </div>
                </li>
            </ul>
            <ul id="houses-list" class="houses-list">
                <li>
                    <div class="new-house">
                        <a href="{{url_for('house.newhouse')}}">发布新房源</a>
                    </div>
                </li>
                <!--<li>-->
                    <!--<a href="">-->
                        <!--<div class="house-title">-->
                            <!--<h3>房屋ID:1 —— 房屋标题1</h3>-->
                        <!--</div>-->
                        <!--<div class="house-content">-->
                            <!--<img src="/static/images/home01.jpg">-->
                            <!--<div class="house-text">-->
                                <!--<ul>-->
                                    <!--<li>位于：西城区</li>-->
                                    <!--<li>价格：￥200/晚</li>-->
                                    <!--<li>发布时间：2016-11-11 20:00:00</li>-->
                                <!--</ul>-->
                            <!--</div> -->
                        <!--</div>-->
                    <!--</a>-->
                <!--</li>-->

            </ul>
        </div>
        <div class="modal fade" id="delete-modal" tabindex="-1" role="dialog" aria-labelledby="delete-label">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title">操作提示</h4>
                        </div>
                        <div class="modal-body">
                            <p>您确定删除房源吗？</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                            <button type="button" class="btn btn-primary modal-delete">确定删除</button>
                        </div>
                    </div>
                </div>
            </div>
        <div class="footer">
            <p><span><i class="fa fa-copyright"></i></span>爱家租房&nbsp;&nbsp;享受家的温馨</p>
        </div> 
    </div>
    
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js"></script>
    <script src="/static/js/template.js"></script>
    <script src="/static/js/ihome/myhouse.js"></script>

</body>
</html>